CREATE DATABASE bEJibun
GO
USE bEJibun
GO

CREATE TABLE Customer(
	CustomerID CHAR(5) PRIMARY KEY CHECK(CustomerID LIKE 'CU[0-9][0-9][0-9]'),
	CustomerName VARCHAR(20) NOT NULL,
	CustomerGender VARCHAR(10) CHECK(CustomerGender IN ('Male' , 'Female')) NOT NULL,
	CustomerPhone CHAR(12) CHECK(CustomerPhone LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	CustomerDOB DATE CHECK(CustomerDOB BETWEEN '1990-01-01' AND GETDATE())
)

CREATE TABLE Staff(
	StaffID CHAR(5) PRIMARY KEY CHECK(StaffID LIKE 'ST[0-9][0-9][0-9]'),
	StaffName VARCHAR(20) NOT NULL,
	StaffGender VARCHAR(10) CHECK(StaffGender IN ('Male' , 'Female')) NOT NULL,
	StaffPhone CHAR(12) CHECK(StaffPhone LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	StaffSalary FLOAT CHECK(StaffSalary > 0) NOT NULL,
)

CREATE TABLE ItemType(
	ItemTypeID CHAR(5) PRIMARY KEY CHECK(ItemTypeID LIKE 'IP[0-9][0-9][0-9]'),
	ItemTypeName VARCHAR(20) CHECK(LEN(ItemTypeName) >= 4) NOT NULL
)

CREATE TABLE Item(
	ItemID CHAR(5) PRIMARY KEY CHECK(ItemID LIKE 'IT[0-9][0-9][0-9]'),
	ItemTypeID CHAR(5) FOREIGN KEY REFERENCES ItemType(ItemTypeID) ON UPDATE CASCADE ON DELETE CASCADE,
	ItemName VARCHAR(100) NOT NULL,
	ItemPrice FLOAT CHECK(ItemPrice > 0) NOT NULL,
	MinPurchase INT NOT NULL
)

CREATE TABLE Vendor(
	VendorID CHAR(5) PRIMARY KEY CHECK(VendorID LIKE 'VE[0-9][0-9][0-9]'),
	VendorName VARCHAR(20) NOT NULL,
	VendorPhone CHAR(12) CHECK(VendorPhone LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	VendorAddress VARCHAR(100) CHECK(VendorAddress LIKE '% Street') NOT NULL,
	VendorEmail VARCHAR(20) CHECK(VendorEmail LIKE '_%@_%.com') NOT NULL
)

CREATE TABLE PurchaseHeader(
	PurchaseID CHAR(5) PRIMARY KEY CHECK(PurchaseID LIKE 'PH[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	VendorID CHAR(5) FOREIGN KEY REFERENCES Vendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseDate DATE DEFAULT GETDATE() NOT NULL,
	ArrivalDate DATE
)

CREATE TABLE PurchaseDetail(
	PurchaseID CHAR(5) FOREIGN KEY REFERENCES PurchaseHeader(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE,
	ItemID CHAR(5) FOREIGN KEY REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	Qty INT CHECK(Qty > 0) NOT NULL,
	PRIMARY KEY(PurchaseID, ItemID)	
)

CREATE TABLE SalesHeader(
	SalesID CHAR(5) PRIMARY KEY CHECK(SalesID LIKE 'SA[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	CustomerID CHAR(5) FOREIGN KEY REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesDate DATE DEFAULT GETDATE()
)

CREATE TABLE SalesDetail(
	SalesID CHAR(5) FOREIGN KEY REFERENCES SalesHeader(SalesID) ON UPDATE CASCADE ON DELETE CASCADE,
	ItemID CHAR(5) FOREIGN KEY REFERENCES Item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	Qty INT CHECK(Qty > 0) NOT NULL,
	PRIMARY KEY(SalesID, ItemID)
)